keys:
  - &user_akijowski age1w5tlx0jcl80eyjshjpqzhv3hm575mswtznkpfm3n9xudadt98eds3hdfp9
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *user_akijowski

